### ISSUE TITLE
SnError when running cffi-gen example. 

### ISSUE THREAD

**Issue by benmoran56** [cheery/lrkit#1]
When running the cffi-gen examples,  all of them error out with an SnError.  This may be caused by changed output of gcc -E? I'm running Arch Linux, with gcc version "6.3.1 20170306". 

```
ben@prime ~/Desktop/cffi-gen $ python2 libSDL2.py
Traceback (most recent call last):
  File "libSDL2.py", line 8, in <module>
    parser.parse(env, ['libSDL2.h'])
  File "/home/ben/Desktop/cffi-gen/parser.py", line 939, in parse
    parser.step(lineno, group, value)
  File "/home/ben/Desktop/cffi-gen/parser.py", line 907, in step
    raise SnError(lineno, error)
parser.SnError: 3646: got PLUS, but expected RIGHT_PAREN, COMMA, SLASH: +
5 lines before error:
extern __attribute__ ((visibility("default"))) int SDL_strcmp(const char *str1, const char *str2);
extern __attribute__ ((visibility("default"))) int SDL_strncmp(const char *str1, const char *str2, size_t maxlen);
extern __attribute__ ((visibility("default"))) int SDL_strcasecmp(const char *str1, const char *str2);
extern __attribute__ ((visibility("default"))) int SDL_strncasecmp(const char *str1, const char *str2, size_t len);

5 lines at error:
extern __attribute__ ((visibility("default"))) int SDL_sscanf(const char *text, const char *fmt, ...) __attribute__ (( format( __scanf__, 2, 2 +1 )));
extern __attribute__ ((visibility("default"))) int SDL_vsscanf(const char *text, const char *fmt, va_list ap);
extern __attribute__ ((visibility("default"))) int SDL_snprintf( char *text, size_t maxlen, const char *fmt, ... ) __attribute__ (( format( __printf__, 3, 3 +1 )));
extern __attribute__ ((visibility("default"))) int SDL_vsnprintf( char *text, size_t maxlen, const char *fmt, va_list ap);
```

**Comment by cheery** [comment]
Hi. I'm happy that someone else likes the idea of converting C headers into json.

It looks like the GCC -E gives you `+ 1` in an attribute. I remember that part of the declaration is ignored anyway, so we could add a grammar rule there to help it out.

I'll look inside into my rules and see whether I get this straightened out.

Edit: Yup! It's cleanly showing up here as well. I'll add the fixes and close this one when done.

**Comment by cheery** [comment]
Ok. I fixed that and couple other things. I would like you to try again after you run `git pull origin master` in your `cffi-gen`. I leave this open. Tell me how it goes!

**Comment by benmoran56** [comment]
Thanks for the fast reply.  I'll give this a try in a few hours when I'm back to the computer. 

I contribute to a Python project that makes heavy use of ctypes bindings, but have been interested in experimenting with cffi in ABI mode. I came across your project and think its awesome.

**Comment by benmoran56** [comment]
I gave it another try, and the SDL2 examples both work fine now. Most of the other examples do throw various errors (not SnErrors). I'm happy to paste those if will help, so please let me know. 

I also tried it out in the REPL on some OpenGL header files, with the following results:
gl.h       OK
glu.h     OK
glext.h  Failed with SnError
glx.h     OK
glcorearb.h OK

Let me know what feedback if any would help.

**Comment by cheery** [comment]
I'll gladly take any feedback. Especially on things that you need to get fixed. Otherwise if some of the generators aren't working and I haven't noticed that, it may be worthwhile to wait until someone needs them to work. Be explicit about what you have found out, and what you need fixes on.

If you have anything more, put up an issue into `cffi-gen` and I'll get back to it. I'll close this one.

For OpenGL, I have a script to retrieve OpenGL headers directly from the Khronos registry XML. The same thing can be done for Vulkan. When doing so it is extremely important to write into "comment" field in JSON where the file is produced from and how. I should make this happen with the `cffi-gen` as well.

On the nature of this project: In practice these files have turned out to be "run cffi-gen once, use everywhere by everybody" -sort of things. The best use case seems to be.. Open the JSON, produce a proxy for the library that lazy-loads definitions as they are needed.

I've had some thoughts about a file format for that use, but it's very difficult to think up something that works better than a zip + json on modern machines, in this use case.

**Comment by benmoran56** [comment]
Will do. I'm just experimenting for the time being, but I'll certainly open tickets with detail when I get stuck. 

I agree with your points. This type of data really should be available, but once it's been generated there isn't much reason to keep doing it. 

I personally really like json, mostly for it's human readability. I think json + zip works just fine until someone comes up with a "better" json.
